apiVersion: v1
kind: Service
metadata:
  name: my-tweet-app
  labels:
    app: my-tweet-app
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 35000
  selector:
    app: my-tweet-app
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: my-tweet-app
spec:
  selector:
    matchLabels:
      app: my-tweet-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-tweet-app
    spec:
      containers:
      - name: my-tweet-app
        image: automatecloud/my-tweet-app:latest
        ports:
        - containerPort: 5000
